[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = SERVER_PRIVATE_KEY
MTU = 1360
PostUp = nft add table ip wireguard; nft add chain ip wireguard wireguard_chain {type nat hook postrouting priority srcnat\; policy accept\;}; nft add rule ip wireguard wireguard_chain counter packets 0 bytes 0 masquerade; nft add chain ip wireguard forward_chain {type filter hook forward priority filter\; policy accept\;}; nft add rule ip wireguard forward_chain tcp flags syn tcp option maxseg size set rt mtu; nft add table ip6 wireguard; nft add chain ip6 wireguard wireguard_chain {type nat hook postrouting priority srcnat\; policy accept\;}; nft add rule ip6 wireguard wireguard_chain counter packets 0 bytes 0 masquerade; nft add chain ip6 wireguard forward_chain {type filter hook forward priority filter\; policy accept\;}; nft add rule ip6 wireguard forward_chain tcp flags syn tcp option maxseg size set rt mtu
PostDown = nft delete table ip wireguard; nft delete table ip6 wireguard
[Peer]
PublicKey = CLIENT_PUBLIC_KEY
AllowedIPs = 10.0.0.2/32