name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build -color=false -on-error=abort ."
        env:
          vpc_id: "$VPC_ID"
          subnet_id: "$SUBNET_ID"
          security_group_id: "$SECURITY_GROUP_ID"
          server_private_key: "${{ secrets.SERVER_PRIVATE_KEY }}"
          server_public_key: "${{ secrets.SERVER_PUBLIC_KEY }}"
          client_public_key: "${{ secrets.CLIENT_PUBLIC_KEY }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
