name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: >
          "packer validate
          -var vpc_id=${{ VPC_ID }}
          -var subnet_id=${{ SUBNET_ID }}
          -var security_group_id=${{ SECURITY_GROUP_ID }}
          -var server_private_key=${{ secrets.SERVER_PRIVATE_KEY }} 
          -var server_public_key=${{ secrets.SERVER_PUBLIC_KEY }} 
          -var client_public_key= ${{ secrets.CLIENT_PUBLIC_KEY }} 
          .          
          "

      - name: Run `packer build`
        id: build
        run: >
          "packer build -var vpc_id=${{ VPC_ID }}
          -var subnet_id=${{ SUBNET_ID }}
          -var security_group_id=${{ SECURITY_GROUP_ID }}
          -var server_private_key=${{ secrets.SERVER_PRIVATE_KEY }}
          -var server_public_key=${{ secrets.SERVER_PUBLIC_KEY }}
          -var client_public_key= ${{ secrets.CLIENT_PUBLIC_KEY }}
          -color=false -on-error=abort ."
        env:          
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
